### ISSUE TITLE
代码都真的测试过了吗？

### ISSUE THREAD

**Issue by eachcan** [easemob/emchat-server-examples#34]
环信的哥们，请把各语言的测试要写完整啊，真的很影响使用你们的产品。目前特别需要 nodejs

**Comment by eachcan** [comment]
我从中午调到现在晚上11点多了，都没有能上传上去一个图片。你们是否要给一个质量还可以的版本？

**Comment by lichunqiang** [comment]
有吐槽的时间都自己写出来了

**Comment by wpajqz** [comment]
我在写golang的sdk了，你们给的代码里面都没有对http请求错误进行处理

**Comment by lynchlee** [comment]
谢谢各位的关注和使用，最近工程师手头事情比较多，都在忙生产线上的事情，没有照顾到这里。大家有问题尽管提出来，我们尽量来处理。
