### ISSUE TITLE
java的发送消息接口不能使用啊

### ISSUE THREAD

**Issue by xadlovezy** [easemob/emchat-server-examples#38]
java的server代码不管from和target是什么，调用接口都返回success,但是app端没有收到消息。。。

**Comment by errordaiwa** [comment]
@xadlovezy message 接口会异步发送消息，如果消息格式没有问题都会返回 success。目前对消息格式的校验不是非常严格，可能会出现一些格式不对的消息，通过了接口校验，但是实际下发没有成功。

**Comment by lynchlee** [comment]
@xadlovezy 可以把你发出去的消息body发一个来看一下么。定位一下问题。

**Comment by qqjbest** [comment]
消息发送了，返回成功，但是没有效果

**Comment by qqjbest** [comment]
Response Body: {"access_token":"YWMtq3lR0BarEeaGRCkwLE0aXPp8AhvFjvIn_B8FrFRKVSeBlNU90","expires_in":5184000,"application":"80331e70-1674-11e6-bc858"}

**Comment by qqjbest** [comment]
java版的

**Comment by qqjbest** [comment]
textMessageBody 中的 getBody方法要修改成这样public ContainerNode<?> getBody() {
        if(!isInit()){
            ObjectNode jsonNode = JsonNodeFactory.instance.objectNode();
            jsonNode.put("type", MsgType.TEXT);
            jsonNode.put("msg", msg);
            this.getMsgBody().put("msg", jsonNode);
            this.setInit(true);
        }

        return this.getMsgBody();
    }
