### ISSUE TITLE
服务端bug

### ISSUE THREAD

**Issue by wszyquan** [easemob/emchat-server-examples#40]
HttpClientRestAPIInvoker和JerseyRestAPIInvoker都有个问题

在请求时会检查body，如下
 if (null == body || !body.validate()) {
            responseWrapper.addError(MessageTemplate.INVALID_BODY_MSG);
        }

这个我看了所有调用的，只有在post和put中才用body，其他的时候都是body为null，所以导致请求无法发出

应该改为
if ((HTTPMethod.METHOD_POST.equalsIgnoreCase(method) || HTTPMethod.METHOD_PUT.equalsIgnoreCase(method))
                && (null == body || !body.validate())) {
            responseWrapper.addError(MessageTemplate.INVALID_BODY_MSG);
        }

测试没有问题

**Comment by wszyquan** [comment]
发现post也有不传body的
改为
if (null != body && !body.validate()) {
			responseWrapper.addError(MessageTemplate.INVALID_BODY_MSG);
		}

**Comment by xuehf** [comment]
jdk必须用1.8的，因为用了nashorn
而myeclipse10，不支持jdk1.8，好纠结
