### ISSUE TITLE
java服务端-根据用户名获取Im用户信息，Object信息出现有误

### ISSUE THREAD

**Issue by nisang** [easemob/emchat-server-examples#42]
调用：IMUserAPI.getIMUsersByUserName("user");
其打印出的信息有误，无法获取到用户信息

[ERROR]: Request body is invalid.
Status: null
Response Body: {}

**Comment by nisang** [comment]
解决方案：
修改HttpClientRestAPIInvoker.java类
一处：
`if( null == body || !body.validate())  {
			responseWrapper.addError(MessageTemplate.INVALID_BODY_MSG);
}`改成
`if( !method.equals("GET") && (null == body || !body.validate()) ) {
			responseWrapper.addError(MessageTemplate.INVALID_BODY_MSG);
}`
原因：GET方法本没有Body，却还要判断是否为空及无效
二处：
`        if( null != body && null != body.getBody() ){
        	((HttpEntityEnclosingRequestBase) request).setEntity(new StringEntity(body.getBody().toString(), "UTF-8"));
        }`改成
`        if( null != body && null != body.getBody() && !method.equals("GET")){
        	((HttpEntityEnclosingRequestBase) request).setEntity(new StringEntity(body.getBody().toString(), "UTF-8"));
        }`
原因：对于GET方法，初始化GET的方法请求客户端，无法setEntity。

**Comment by errordaiwa** [comment]
@nisang 感谢！

@yaobaobao 看一下如何修复。
