### ISSUE TITLE
java端发送消息出现多种错误 Request body is invalid | msg must be provided。

### ISSUE THREAD

**Issue by nisang** [easemob/emchat-server-examples#44]
1
.Request body is invalid.
2.
Response Body: {"error":"illegal_argument","timestamp":1472784124017,"duration":0,"exception":"java.lang.IllegalArgumentException","error_description":"msg must be provided"}

解决方案如下

**Comment by nisang** [comment]
根据文档说明：http://docs.easemob.com/im/100serverintegration/50messages
已发布透传消息为例来解决方案：

**Comment by nisang** [comment]
对于问题1：Request body is invalid
原因在于对可选参数的做了不为空校验。
修改：com.che.easemob.server.comm.body.MessageBody.validate

`StringUtils.isNotBlank(targetType) && isValidTargetType() && ArrayUtils.isNotEmpty(targets) && StringUtils.isNotBlank(from)`
改成
`tringUtils.isNotBlank(targetType) && isValidTargetType() && ArrayUtils.isNotEmpty(targets)`
因为文档说明from参数可为空，为空清空下默认发送用户为admin，这在某些应用场景下，符合业务

**Comment by nisang** [comment]
对于问题2：msg must be provided
Request构造与文档说明的构造参数有很大差别。
修改1:
`com.che.easemob.server.comm.body.MessageBody`
新增一ObjectNode 属性为msg的数据
`private ObjectNode msg;`

修改2：
`com.che.easemob.server.comm.body.CommandMessageBody.getBody()`
`if(!this.isInit()){
			this.getMsgBody().put("type", MsgType.CMD);
			this.getMsgBody().put("action", action);
			this.setInit(true);
		}`
改成
`		if(!this.isInit()){
			ObjectNode msgBody = this.getMsgBody().putObject("msg");
			msgBody.put("type", MsgType.CMD);
			msgBody.put("action", action);
			this.setInit(true);
		}`
.
修改后，提交测试，返回ResonpseBody内容为
`Status: 200
Response Body: {"action":"post","application":"4c6f7f70-65cf-11e6-853c-1f1cc5aefd00","path":"/messages","uri":"https://a1.easemob.com/{组织名称}/{应用名称}/messages","data":{"1111111":"success"},"timestamp":1472784687135,"duration":0,"organization":"1111111111","applicationName":"11111"}
`

**Comment by errordaiwa** [comment]
@nisang 感谢！

@yaobaobao 看一下这些问题吧。
