### ISSUE TITLE
Java 的SDK不能正确发送消息中带ext

### ISSUE THREAD

**Issue by rainygoblin** [easemob/emchat-server-examples#79]
目前ext是String类型，传入json的string，服务器报错。

**Comment by shanjingheng** [comment]
使用最新的emchat-server-java，使用如下方式发送string类型消息。新版本的使用方式在test文件夹中有详细用例
`   @Test
    public void send() {
        Msg msg = new Msg();
        MsgContent msgContent = new MsgContent();
        msgContent.type(MsgContent.TypeEnum.TXT).msg("helloword");
        UserName userName = new UserName();
        userName.add("qwqwqww");
        msg.from("stringa").target(userName).targetType("users").msg(msgContent);
        Object result = easemobSendMessage.sendMessage(msg);
        System.out.println(result);
    }`

**Comment by Faiz2** [comment]
所以所就不能传ext扩展消息啦？我的天我还找了半天

**Comment by rainygoblin** [comment]
是JAVA 的SDK的问题

**Comment by errordaiwa** [comment]
@rainygoblin @Faiz2 抱歉，应该是 swagger 的定义文件类型标记错了，ext 应该是 JsonObject。我们会尽快更新 SDK。

**Comment by errordaiwa** [comment]
Fix in #85
