### ISSUE TITLE
java 原来版本的示例，发送获取token请求时抛出异常ValidatorException

### ISSUE THREAD

**Issue by Aiome** [easemob/emchat-server-examples#81]
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: No trusted certificate found

示例是去年11月下载的。
我从来没有更改过证书，不知道环信这边是不是更改了证书。
emchat-server-java\src\main\resources\cacert
这里面也有相应的证书

**Comment by errordaiwa** [comment]
@Aiome 是的，之前的证书有一些浏览器无法兼容，我们在 1 月份更新了一个兼容性更好的证书，重新导入一下就可以了。

**Comment by Aiome** [comment]
@errordaiwa 那请问我应该去哪里再下载这个证书呢

**Comment by errordaiwa** [comment]
@Aiome README 里有获取方式，也可以直接使用新代码里的 cacert 文件。

**Comment by Aiome** [comment]
@errordaiwa 我按照README操作了一波,
是否信任此证书? [否]:  是
证书已添加到密钥库中

不知道怎么获得到emchat-server-java\src\main\resources\cacert中的这两个文件
mykeystore.jks
cacerts

我又去新代码里找，resources里面也没有你说的那个制作好的证书。。老哥求指点。

**Comment by errordaiwa** [comment]
@Aiome resources 里的证书链被误删了，已经恢复了，更新下代码应该就能看到

**Comment by Aiome** [comment]
@errordaiwa 刚看到,我已经解决了,我在这贴下我的解决办法吧,

1.用keytool生成.jks文件
Keytool -genkey -alias "certificate" -keyalg "RSA" -keystore "f:\test.jks"
2.将环信下载的证书导入到.jks证书库就OK了
Keytool -import -keystore f:\test.jks -file C:\Users\Aiome\Desktop\-easemobcom.crt

第一波操作是因为找不到生成的keystore,后来发现可以把keystore生成到指定目录,
