### ISSUE TITLE
deleteFriendSingle   error

### ISSUE THREAD

**Issue by junspace** [easemob/emchat-server-examples#87]
@Override
	public Object deleteFriendSingle(final String userName,final String friendName) {
		return responseHandler.handle(new EasemobAPI() {
			@Override
			public Object invokeEasemobAPI() throws ApiException {
				return api.orgNameAppNameUsersOwnerUsernameContactsUsersFriendUsernameDelete(OrgInfo.ORG_NAME,OrgInfo.APP_NAME,TokenUtil.getAccessToken(),userName,friendName);
			}
		});
	}
调用删除好友方法，OrgInfo.ORG_NAME,OrgInfo.APP_NAME,这两个都是有值并且正确的，可是ResponseHandler 类中的handle处理的时候却报ApiException e 异常"error":"organization_application_not_found","exception":"org.apache.usergrid.rest.exceptions.OrganizationApplicationNotFoundException","error_description":"Could not find application for ***/{app_name} from URI: ***/{app_name}/users/contacts/users
{app_name}这个值没取到，这是什么原因呢？

**Comment by junspace** [comment]
这个项目还有人维护吗？我调别的接口都能把OrgInfo.ORG_NAME,OrgInfo.APP_NAME这两个值传过去，这个接口为啥就报appname没传过去呢？

**Comment by errordaiwa** [comment]
@junspace SDK 在这个接口上实现有点问题，appname 多加了一个空格，我们会尽快修复。

**Comment by junspace** [comment]
恩恩，多谢哈，今天可以修复吗？麻烦了哈

**Comment by errordaiwa** [comment]
@junspace 已经修复，麻烦试一下

**Comment by junspace** [comment]
删除成功了，多谢仁兄！
